spring:
  application:
    name: crawler-jd-headless
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12356

indexUrl: https://www.jd.com/